export const defaultMuseum = {
    origin: { x: 0, y: 0 },
    startingPoint: { x: 7, y: 9 },
    paintings: [
        {
            orientation: { x: 0, y: 1 },
            adn: [
                { color: 101, opacity: 3, r: 14, x: 62, y: 52 },
                { color: 24, opacity: 3, r: 6, x: 45, y: 21 },
                { color: 42, opacity: 2, r: 15, x: 23, y: 59 },
                { color: 169, opacity: 3, r: 7, x: 28, y: 21 },
                { color: 15, opacity: 1, r: 15, x: 11, y: 2 },
                { color: 247, opacity: 1, r: 13, x: 49, y: 18 },
                { color: 224, opacity: 2, r: 7, x: 37, y: 38 },
                { color: 141, opacity: 1, r: 15, x: 35, y: 18 },
                { color: 42, opacity: 1, r: 7, x: 43, y: 31 },
                { color: 51, opacity: 1, r: 12, x: 57, y: 15 },
                { color: 0, opacity: 1, r: 6, x: 40, y: 18 },
                { color: 205, opacity: 0, r: 3, x: 50, y: 32 },
                { color: 183, opacity: 1, r: 2, x: 32, y: 22 },
                { color: 242, opacity: 0, r: 7, x: 63, y: 60 },
                { color: 99, opacity: 0, r: 8, x: 16, y: 3 },
                { color: 1, opacity: 0, r: 10, x: 48, y: 59 },
                { color: 56, opacity: 0, r: 14, x: 43, y: 56 },
                { color: 232, opacity: 3, r: 5, x: 32, y: 40 },
                { color: 84, opacity: 1, r: 5, x: 23, y: 35 },
                { color: 1, opacity: 0, r: 14, x: 30, y: 58 },
                { color: 226, opacity: 1, r: 6, x: 3, y: 51 },
                { color: 199, opacity: 0, r: 8, x: 8, y: 16 },
                { color: 232, opacity: 1, r: 3, x: 32, y: 11 },
                { color: 249, opacity: 0, r: 2, x: 46, y: 12 },
                { color: 190, opacity: 1, r: 7, x: 4, y: 47 },
                { color: 50, opacity: 1, r: 12, x: 6, y: 38 },
                { color: 197, opacity: 1, r: 7, x: 31, y: 41 },
                { color: 247, opacity: 3, r: 5, x: 31, y: 41 },
                { color: 208, opacity: 0, r: 2, x: 16, y: 32 },
                { color: 84, opacity: 1, r: 1, x: 26, y: 34 },
                { color: 206, opacity: 0, r: 11, x: 58, y: 4 },
                { color: 50, opacity: 1, r: 4, x: 32, y: 4 },
                { color: 0, opacity: 1, r: 3, x: 36, y: 10 },
                { color: 2, opacity: 0, r: 15, x: 49, y: 63 },
                { color: 240, opacity: 1, r: 2, x: 24, y: 44 },
                { color: 140, opacity: 0, r: 2, x: 23, y: 49 },
                { color: 198, opacity: 0, r: 4, x: 57, y: 37 },
                { color: 232, opacity: 0, r: 3, x: 11, y: 41 },
                { color: 233, opacity: 0, r: 6, x: 63, y: 48 },
                { color: 249, opacity: 0, r: 5, x: 31, y: 17 },
            ],
            downsizeId: '5f8edd6bc20a',
            paintingId: '5631986051842048',
            id: '7751af8c',
            cell: { x: 7, y: 6 },
        },
    ],
    signs: ['\nYou found\n"La joconde"\n!', 'aaa'],
    startingOrientation: { x: 0, y: -1 },
    grid: [
        [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        [
            false,
            false,
            false,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        [
            false,
            false,
            false,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        [
            false,
            false,
            false,
            false,
            true,
            false,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        [
            false,
            false,
            false,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        [
            false,
            false,
            false,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        [
            false,
            false,
            false,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        [
            false,
            false,
            false,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        [
            false,
            false,
            false,
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
        ],
        [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
    ],
}
