import '../service/map/__tests__/expandGrid.spec.ts'
import '../service/map/__tests__/reduceGrid.spec.ts'
import '../service/map/__tests__/placeWall.spec.ts'
import '../service/map/__tests__/rectWall.spec.ts'
import '../service/aStart/__tests__/aStar.spec.ts'
// import '../store/reducer/__tests__/consistency.spec.ts'
